# Generated by Django 3.0.8 on 2020-07-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20200728_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='fecha_termino',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
    ]
