# Generated by Django 3.0.8 on 2020-07-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20200728_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
