# Generated by Django 3.0.8 on 2020-07-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_trabajo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
