# Generated by Django 3.0.8 on 2020-07-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='duracion',
            field=models.TimeField(null=True),
        ),
    ]
