# Generated by Django 3.0.8 on 2020-07-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_auto_20200729_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='duracion',
            field=models.DurationField(null=True),
        ),
    ]
