# Generated by Django 3.0.8 on 2020-07-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20200730_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='duracion',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
