# Generated by Django 3.0.8 on 2020-07-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_auto_20200730_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='duracion',
            field=models.TimeField(null=True),
        ),
    ]
