# Generated by Django 3.0.8 on 2020-07-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_auto_20200730_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='duracion',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
    ]
